// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lychulllezubdosaqqlh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5Y2h1bGxsZXp1YmRvc2FxcWxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNDc2ODYsImV4cCI6MjA2MDcyMzY4Nn0.8cT_20g3he4F0pQlyZYGpwhbJrI0heID8cpqSZuTQXw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);